### ISSUE TITLE
IndexError: list index out of range - freq & sfs

### ISSUE THREAD

**Issue by yzliu01** [simonhmartin/genomics_general#106]
Hi Simon,
I am trying your scripts to output sfs data but I got an error (`IndexError: list index out of range`) when first testing with freq.py. The execution could run afterwards. Details are as below. I am not clear where to fix this error?
Looking forward to your tips.
Best,

```
$python $freq_py -g $geno -f phased -t 4 -p pop1 --popsFile pops.txt
scaffold        position        pop1

Starting 4 worker threads

Closing worker threads
Process Process-1:
Traceback (most recent call last):
  File "/home/xx/miniforge3/envs/bioproject/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/xx/miniforge3/envs/bioproject/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xx/bin/SM_genomics_general/freq.py", line 42, in freqs_wrapper
    window = genomics.parseGenoFile(fileSlice, headerLine, names=sampleData.indNames)
  File "/home/xx/bin/SM_genomics_general/genomics.py", line 1947, in parseGenoFile
    for siteData in reader.siteBySite(asDict=extractSpecificGTs):
  File "/home/xx/bin/SM_genomics_general/genomics.py", line 1922, in siteBySite
    yield parseGenoLine(line, self.names, self.scafCol, self.posCol, self.firstSampleCol, self.type, self.splitPhased, asDict,
  File "/home/xx/bin/SM_genomics_general/genomics.py", line 1874, in parseGenoLine
    GTstring = lineData[-1]
IndexError: list index out of range
1 slices queued | 3 slices analysed | 0 slices written | 0 lines written
1 slices queued | 3 slices analysed | 0 slices written | 0 lines written
......
```

**Comment by simonhmartin** [comment]
Hi, the script seems to have found a line in the geno file that does not have the standard form of `scaffold position genotype1 genotype2 etc` I would recommend trying the script with small subsets of your input file and increasing the size until you find the line that is causing the error.

**Comment by yzliu01** [comment]
Hi, thanks a lot. Indeed, it's for this reason. I solved it after looking into the geno file in which there are empty lines.
