### ISSUE TITLE
error in distMat.py

### ISSUE THREAD

**Issue by MafaldaSFerreira** [simonhmartin/genomics_general#11]
Hi,

I've been trying to use distMat.py to calculate pairwise divergence between several individuals. It works fine with two individuals, with the following command: 

`/usr/bin/python ~/my_programs/genomics_general_v3/distMat.py -g wg_filtered_wHead.geno.gz -f diplo --outFormat raw --windType cat --samples species1,species2 -o output_file`

However, when I try to use more than two individuals (or for all the species in the file), like so:

`/usr/bin/python ~/my_programs/genomics_general_v3/distMat.py -g wg_filtered_wHead.geno.gz -f diplo --outFormat raw --windType cat --samples species1,species2,species3 -o output_file`

...the script crashes after a while (it gives the normal number of windows queued info), with the following error:

> ...
> 0 windows queued 0 results received 0 results written.
> 0 windows queued 0 results received 0 results written.
> 0 windows queued 0 results received 0 results written.
> 0 windows queued 0 results received 0 results written.
> 0 windows queued 0 results received 0 results written.
> Traceback (most recent call last):
>   File "/home/mafalda_ferreira/my_programs/genomics_general_v3/distMat.py", line 293, in <module>
>     windowQueue.put((windowsQueued,window))
>   File "/usr/lib/python2.7/multiprocessing/queues.py", line 392, in put
>     return send(obj)
> IOError: bad message length
> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/mafalda_ferreira/my_programs/genomics_general_v3/distMat.py", line 102, in checkStats
>     print >> sys.stderr, windowsQueued, "windows queued", resultsReceived, "results received", resultsWritten, "results written."
> AttributeError: 'NoneType' object has no attribute 'stderr'

I'm not sure why this is happening though... Because the two individuals comparison works, I'm not sure what could be causing it! Do you have any idea? 

Thank you!

**Comment by simonhmartin** [comment]
I'm not sure what the problem could be. Could you include just a short example from your input file (first 10 lines)?

**Comment by MafaldaSFerreira** [comment]
Here it is:

[head10.geno.txt](https://github.com/simonhmartin/genomics_general/files/2651116/head10.geno.txt)

**Comment by MafaldaSFerreira** [comment]
Here it is (I could attach a region with less missing data if that's useful!)
[head10.geno.txt](https://github.com/simonhmartin/genomics_general/files/2651119/head10.geno.txt)

**Comment by simonhmartin** [comment]
The file appears to be fine. The other common issue with this script is running out of memory, which can happen using --windType cat if you have a very large input file. You can test that by using a subset of your file.

**Comment by biozhangzhou** [comment]
Traceback (most recent call last):
  File "/home/zhzhiming/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "../../../20190222/genomics_general-master/distMat.py", line 37, in stats_wrapper
    pairDistDict = aln.indPairDists(includeSameWithSame=includeSameWithSame)
TypeError: indPairDists() got an unexpected keyword argument 'includeSameWithSame'
^[[A^CTraceback (most recent call last):
  File "../../../20190222/genomics_general-master/distMat.py", line 331, in <module>
    sleep(1)
KeyboardInterrupt

#####
Sorry ,I cann't even run the example command; so i want to ask which parametnts should be in the command , and how many sites and inds will be ok for this scripts?  Thanks a lot.

**Comment by simonhmartin** [comment]
The error refers to new functionality I added recently. If you download the latest version of the genomics.py module that should fix it.
