### ISSUE TITLE
Error in popPairDist

### ISSUE THREAD

**Issue by kfpbennett** [simonhmartin/genomics_general#14]
Hi Simon,

I am having the same issue with popPairDist that Robert (rfitak) described in December:

Traceback (most recent call last):
  File "/opt/python/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/python/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "popgenWindows.py", line 58, in stats_wrapper
    values = [round(statsDict[stat], roundTo) for stat in stats]
KeyError: 'dxy_pop3_pop4'

The popDist analysis of pi seems to be working fine. Any insight would be appreciated. Thanks!

Kevin

**Comment by simonhmartin** [comment]
Hi Kevin,
Thanks for reminding me about this problem. It was just a small bug that caused the script to not do pairwise (popPairDist) analyses unless you had ALSO requested the within population analysis (popDist). That should be fixed now. 
-Simon

**Comment by rafmarcondes** [comment]
I'm getting that same error but in popgenWindows.py. It runs for a while without issues but then gives me the below and stays stuck in that window forever. Repo downloaded today, Python 2.7.16.

```
Process Process-1:
Traceback (most recent call last):
  File "/opt/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Rafael/Dropbox/thamno_dna/simon-martin-scripts/popgenWindows.py", line 63, in stats_wrapper
    values = [round(statsDict[stat], roundTo) for stat in stats]
KeyError: 'dxy_asp_par'

50805 windows queued, 50749 results received, 50749 results written.

50805 windows queued, 50749 results received, 50749 results written.
```

**Comment by simonhmartin** [comment]
I think I might know how to fix this bug. Could you share the command you used? Thanks

**Comment by rafmarcondes** [comment]
> I think I might know how to fix this bug. Could you share the command you used? Thanks

Hi Simon,

It's been a while, but I'm playing around with your scripts again, and still finding this issue where opgenWindows.py gets stuck forever in a window. This is my command:

`python3 /home/rmarco3/genomics_general-master/popgenWindows.py -g filtered_for_fst_27jan2020.geno -o dinVpar.stats --popsFile pops_file_for_martin -p par -p din -f phased --verbose --windType coordinate -w 10000`

**Comment by simonhmartin** [comment]
Hmm this might take a bit of back-and-forth between us to figure out. First, can you confirm:
1. You're using the latest versions of `genomics.py` and `popgenWindows.py`?
2. You're only specifying two populations: `par` and `din`, and yet the script is giving an error trying to find `dxy_asp_par`?

**Comment by rafmarcondes** [comment]
Hi Simon. Sorry to come back to this after a long time. I was able to make this work at some point, but am now again running into the issue where popgenWindows.py gets stuck forever in one window. This happens with Python 2.7.14 as well as 3.4.2. Repo downloaded on 1/25/2021. Below is the command I used, and in the Dropbox folder below are all the files you would need to replicate it.

Tangentially, the command is running one only 1 node, despite me having requested multiple. You can see that at the tail of the log file that is also on Dropbox

> python /home/rmarco3/genomics_general-master/popgenWindows.py -g ALL-SITES-FILTERED.geno -o conVcon-allsites-batch1-python2.stats --popsFile con_by_bright_pops -p d -p b --verbose --windType coordinate -w 10000 --writeFailedWindows  --inferPloidy -f phased --threads 60 --include chrom-batch1

https://www.dropbox.com/sh/4sq8c5kpgzasnkj/AAC8eT82IjcFPpiOQA2fe19Ua?dl=0

**Comment by simonhmartin** [comment]
Hi Rafael, I'm finally looking at this. I see the  script is failing after successfully analysing over 50k windows (over 500 Mb of the genome). To save time, it would be very useful to know which chromosome it fails on. That should be possible to get from the output, or otherwise could be worked out by considering how many chromosomes go into the first 500 Mb of the genome.
Thanks,
Simon

**Comment by rafmarcondes** [comment]
Hi Simon,

Thank you so much for looking into this. I can't tell which chromosome it
fails on by looking at the output because there's no output. It creates the
output file but never writes anything to it (at least until it hits the
cluster kill time of 72 hrs).

But ordering the chromosomes by size, it looks like 500 Mb would be reached
in chromosome 26, assuming the script proceeds alphabetically
(1,10,11...2,20,21...), or in chromosome 5 assuming it goes
numerically (1,2,3...)

I have attached the genome .fai file.

Thanks,

Rafa

*--*
*Rafael Sobral Marcondes, Ph.D.*

Pronouns: he/him


*"Eu quase que nada não sei. Mas desconfio de muita coisa"*
*"I almost don't know nothing. But I suspect many things"*
  -João Guimarães Rosa, Brazilian novelist
(Portuguese original and free English translation by me)

**Comment by simonhmartin** [comment]
Thanks. The script works in the same order as the VCF, which is usually the same order as the .fai. But i don't see the attachment...

**Comment by rafmarcondes** [comment]
Here it is
[Tcae_B94639.pseudo.upper.masked.fasta.fai.zip](https://github.com/simonhmartin/genomics_general/files/6593381/Tcae_B94639.pseudo.upper.masked.fasta.fai.zip)

**Comment by simonhmartin** [comment]
Ok so I've been unable to recreate your issue. I ran the script and it worked fine with no problems. Initially I ran each chromoosme separately, and then ran the whole thing, which took only about 3 hours on 6 cores. I think a small number of cores is often better with my scripts, otherwise there is a lot of time wasted on managing the parallelisation itself. I still don't know what the problem was that caused the script to crash for you. Maybe try with a small number of cores just to rule that out as the problem.

**Comment by rafmarcondes** [comment]
I have tried multiple times to run it with one or a small number of cores
and ran into the same issue. I'll try to run each chromosome separately and
see what happens and let you know. Thanks for your time looking into this
though!

Rafa

*--*
*Rafael Sobral Marcondes, Ph.D.*

Pronouns: he/him


*"Eu quase que nada não sei. Mas desconfio de muita coisa"*
*"I almost don't know nothing. But I suspect many things"*
  -João Guimarães Rosa, Brazilian novelist
(Portuguese original and free English translation by me)

**Comment by simonhmartin** [comment]
Strange. The only thing I changed is that I unzipped your .geno file and then zipped using bgzip (which makes extraction of individual chromosomes easy), but I don't see how that would cause any problems.

**Comment by rafmarcondes** [comment]
Hi Simon, me again. I'm trying to run one chromosome at at a time, and having trouble. For example for some chromosomes, I think the shorter ones. For example:

[rmarco3@mike2 rmarco3]$  python /home/rmarco3/genomics_general-master/popgenWindows.py -g ALL-SITES-FILTERED.geno -o conVcon-chrZ.fst --popsFile con_by_bright_pops -p d -p b --verbose --windType coordinate -w 10000 --writeFailedWindows  --inferPloidy -f phased --threads 1 --include chr33
1 scaffolds will be analysed.
Starting 1 worker threads

0 windows queued, 0 results received, 0 results written.

0 windows queued, 0 results received, 0 results written.

0 windows queued, 0 results received, 0 results written.

0 windows queued, 0 results received, 0 results written.

And that goes on indefinitely. The length of chr33 is 22248, so I would expect it to write at least 2 windows, with --writeFailedWindows. For longer chromosomes it seems to work fine.

**Comment by simonhmartin** [comment]
I think it's called chr33_cl in your vcf

**Comment by rafmarcondes** [comment]
Yes, the file is named chr33 but its only content is one line that
says chr33_cl

Rafa

*--*
*Rafael Sobral Marcondes, Ph.D.*

Pronouns: he/him


*"Eu quase que nada não sei. Mas desconfio de muita coisa"*
*"I almost don't know nothing. But I suspect many things"*
  -João Guimarães Rosa, Brazilian novelist
(Portuguese original and free English translation by me)

**Comment by simonhmartin** [comment]
Oh right. Ok try the following, which works for me:

Zip geno file with bgzip and index it (you only need to do this once)
```
bgzip -p ALL-SITES-FILTERED.geno
tabix -p vcf ALL-SITES-FILTERED.geno.gz
```

Extract one chromosome and pipe to popgenWindows
```
tabix -h ALL-SITES-FILTERED.geno.gz chr33_cl |  python popgenWindows.py --popsFile con_by_bright_pops -p d -p b -w 10000 --inferPloidy -f phased --threads 1
```
