### ISSUE TITLE
issue with parseVCF.py reading my vcf

### ISSUE THREAD

**Issue by jenncoughlan** [simonhmartin/genomics_general#16]
Hi Simon!
I'm running into an issue reading my vcf into the parseVCF.py program. 
When I run: python3.5 ~/genomics_general-master/VCF_processing/parseVCF.py -i $input.vcf.gz --minQual 30 --skipIndels --gtf flag=DP min=5 | gzip > $output.geno.gz

It returns the error message:
Traceback (most recent call last):
  File "/nas/longleaf/home/jcoug/genomics_general-master/VCF_processing/parseVCF.py", line 266, in <module>
    headData = getHeadData(args.inFile)
  File "/nas/longleaf/home/jcoug/genomics_general-master/VCF_processing/parseVCF.py", line 156, in getHeadData
    return parseHeaderLines(headLines)
  File "/nas/longleaf/home/jcoug/genomics_general-master/VCF_processing/parseVCF.py", line 134, in parseHeaderLines
    if line.startswith("##contig"):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

I don't *think* there's anything unusual about the format of my vcf, but I've included the first few lines in case you see something.
##fileformat=VCFv4.2
##ALT=<ID=NON_REF,Description="Represents any possible alternative allele at this location">
##FILTER=<ID=LowQual,Description="Low quality">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Approximate read depth (reads with MQ=255 or with bad mates are filtered)">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=MIN_DP,Number=1,Type=Integer,Description="Minimum DP observed within the GVCF block">
##FORMAT=<ID=PGT,Number=1,Type=String,Description="Physical phasing haplotype information, describing how the alternate alleles are phased in relation to one another">
##FORMAT=<ID=PID,Number=1,Type=String,Description="Physical phasing ID information, where each unique ID within a given sample (but not across samples) connects records within a phasing group">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Normalized, Phred-scaled likelihoods for genotypes as defined in the VCF specification">
##FORMAT=<ID=RGQ,Number=1,Type=Integer,Description="Unconditional reference genotype confidence, encoded as a phred quality -10*log10 p(genotype call is wrong)">
##FORMAT=<ID=SB,Number=4,Type=Integer,Description="Per-sample component statistics which comprise the Fisher's Exact Test to detect strand bias.">

Any help you can offer is appreciated!
Thanks very much,
Jenn

**Comment by simonhmartin** [comment]
I think this is a python version issue. I have probably not yet ported this script to python 3. Could you try in python 2.7?

**Comment by jenncoughlan** [comment]
Ah! Thanks so much- seems to be running smoothly now!
