### ISSUE TITLE
AssertionError: Sample ploidy (2) doesn't match number of sequences (3)

### ISSUE THREAD

**Issue by fushike** [simonhmartin/genomics_general#18]
Hi Simon,
I used popgenWindows.py to analysize the pi and fst of two populations with the commnad： 
python2 /public/home/kefushi/software/genomics_general/popgenWindows.py -w 100000 -s 5000 -m 100 -g /public/home/kefushi/data/dbm/bi_o_gene20k_095_005.recode.geno.gz -o /public/home/kefushi/data/dbm/NA_AF.csv -f pairs -T 1 -p NA NA_M_11,NA_M_12,NA_M_5,NA_M_6,NA_M_8 -p AF POP10_AF_3,POP10_AF_4,POP10_AF_5,POP10_AF_7,POP10_AF_8

but it came up with error:
Traceback (most recent call last):
  File "/public/home/kefushi/software/miniconda3/envs/python2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/public/home/kefushi/software/miniconda3/envs/python2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/public/home/kefushi/software/genomics_general/popgenWindows.py", line 39, in stats_wrapper
    Aln = genomics.genoToAlignment(window.seqDict(), sampleData, genoFormat = genoFormat)
  File "/public/home/kefushi/software/genomics_general/genomics.py", line 1019, in genoToAlignment
    if ploidy is not None: assert len(seqList) == ploidy, "Sample ploidy (" + str(ploidy) + ") doesn't match number of sequences (" + str(len(seqList)) + ")"
AssertionError: Sample ploidy (2) doesn't match number of sequences (3)

1519 windows queued, 1514 results received, 0 results written.

1519 windows queued, 1514 results received, 0 results written.

1519 windows queued, 1514 results received, 0 results written.

=========================================================

But if I change ploidy from 2 (which is the right number) into 3, it works. 

Any suggerstions here? 

Cheers,

Fushi

**Comment by simonhmartin** [comment]
Sorry for the delay. I'm not sure what the problem is, but I suspect it might be something odd about teh way your genotypes are encoded. Are you sure all genotypes are single nucleotides (like "A/T") and not indels (like "A/TAA")?

**Comment by fushike** [comment]
Hi Simon,
I checked the genotypes of my samples and didn't find any individuals with indels. 
Here is an example of the genotype data
NewChr10        255917  A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/T     A/A     A/A     A/A     A/A     A/T     A/A     A/A     A/A  A/T      N/N     A/A     A/A     A/A     A/A     A/A     A/A     N/N     A/A     A/T     A/A     A/A     A/A     A/T     A/A     N/N     A/A     A/A     A/A     A/A     A/A     A/A     A/A A/A      A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     A/A     N/N     A/A     A/A     A/A     A/A     A/A     A/A     A/A A/A      A/A     A/A     A/A     A/A     A/T     N/N     A/T     A/A

**Comment by simonhmartin** [comment]
Hi Fushi,
This is a puzzle. The only thing I can recommend is to make reduced versions of your geno file with say 1000 lines, 2000 lines etc, to try to find out which line in particular is causing the script to fail.

**Comment by rafmarcondes** [comment]
Hi Fushi and Simon,

Did you end up finding a solution for this? I'm encountering the same error. I converted my vcf to geno using parseVCF.py --skipIndels.

Here's my command:

`python /home/rmarco3/bin/simon-martin-scripts/popgenWindows.py -T 4 -g asp_con_din_par_quality_filtered_ONLY.geno --windType coordinate -w 50000 -s 25000 --popsFile pops_file_for_martin -p asp -p par -f pairs --verbose -o simon_stats_aspVpar`

Thanks for any help!

**Comment by fushike** [comment]
Hi Rafael,

I am not sure if it will work in your system, but I remove the -f pairs command and find it works well.

hope it will help,

Best 

Fushi

From: Rafael Marcondes
Date: 2020-07-11 03:16
To: simonhmartin/genomics_general
CC: fushike; Author
Subject: Re: [simonhmartin/genomics_general] AssertionError: Sample ploidy (2) doesn't match number of sequences (3) (#18)
Hi Fushi and Simon,
Did you end up finding a solution for this? I'm encountering the same error. I converted my vcf to geno using parseVCF.py --skipIndels.
Here's my command:
python /home/rmarco3/bin/simon-martin-scripts/popgenWindows.py -T 4 -g asp_con_din_par_quality_filtered_ONLY.geno --windType coordinate -w 50000 -s 25000 --popsFile pops_file_for_martin -p asp -p par -f pairs --verbose -o simon_stats_aspVpar
Thanks for any help!

**Comment by fushike** [comment]
> Hi Fushi and Simon,
> 
> Did you end up finding a solution for this? I'm encountering the same error. I converted my vcf to geno using parseVCF.py --skipIndels.
> 
> Here's my command:
> 
> `python /home/rmarco3/bin/simon-martin-scripts/popgenWindows.py -T 4 -g asp_con_din_par_quality_filtered_ONLY.geno --windType coordinate -w 50000 -s 25000 --popsFile pops_file_for_martin -p asp -p par -f pairs --verbose -o simon_stats_aspVpar`
> 
> Thanks for any help!

Hi Rafael, 

In the README.md file, you can find -f pairs refers to genotype without a line between alleles. And "-f phased", should be proper in the situation with or without phasing.

* Genotypes can be incoded in various ways, as indicated by the `-f` flag.
`-f phased` means that genotypes include phase information (but they don't necessarily need to actually be phased):
```
scaffold1  1        A/A       G/G       G|A
```
`-f pairs` is the same, but without the phase indicator:
```
scaffold1  1        AA       GG       AG
```
`-f haplo` means that genotypes are haploid bases:
```
scaffold1  1        A       G       G
```
`-f diplo` means that genotypes are single bases denoting the diploid genotype, using ambiguity codes for heterozygotes:
```
scaffold1  1        A       G       R


Best,

Fushi

**Comment by rafmarcondes** [comment]
Thanks, Fushi. Yea, it's working now with -f phased.
