### ISSUE TITLE
Error with distMat.py

### ISSUE THREAD

**Issue by jkreinz** [simonhmartin/genomics_general#29]
Hi Simon,

Thanks for making these scripts public! I've found them extremely helpful. I'm trying to implement your script for pairwise distance matricies (--window cat) style but I either get the program finishing with no output, or this error attached below. 

Here is the command I've been using: `python3 distMat.py -g ../herb_finalfilt.geno -f phased --windType cat -o herb_finalfilt_raw.dist -w 100000 -s 100000 -m 250 --outFormat raw`

You'll notice I made the min number of SNPs rather small as I was worried too many windows were being thrown out due to the output msgs "0 windows queued | 0 results received | 0 results written.

```
Traceback (most recent call last):
  File "distMat.py", line 314, in <module>
    windowQueue.put((windowsQueued,window))
  File "/usr/lib64/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 204, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 397, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
```

Thanks!!!

**Comment by simonhmartin** [comment]
Hi,
I'm not sure but I think this issue might be caused by a difference between python 2 and 3 in writing plain text vs bytes. I usually write to stdout, so might have missed this. I have just pushed up a version that will _hopefully_ fix the issue.  
The other thing to point out is that with `--windTypw cat`, the script will ignore the `-w` or `-s`. It will actually just include ALL sites in a single window and output a single distance matrix. This can use **huge** amounts of memory if you have a large input file, so be careful. If you want individual smaller windows, rather use `--windtype coordinate` or `--windType sites`. These windows will always end at scaffold boundaries. There is currently no option to make individual windows but bridging across scaffold boundaries.

**Comment by simonhmartin** [comment]
Also note that with `--windType cat` it still spits out the "0 windows queued | 0 results received | 0 results written" while it is running. This just means it is still reading/processing the one large window.

**Comment by stubbsrl** [comment]
Just to jump in here because I also had a few hiccups with this script. First, I couldn't get it to run until I drastically reduced the number of species being compared. Also, I added the very useful threads command (-T).  I used the following command where I set species with the --samples command and seperated them by a space.  Doing these steps worked with a rather large vcf, so hopefully this helps others. 

python3 distMat.py -g $GENO -f phased -T 8 --windType cat --samples Sample1 Sample2 Sample 3 -o $OUT/${NAME}.dist.txt

Here's my question: I expected the diagonal of the resulting matrix to be zero because that should be where the species is being compared to itself. But instead I got the values of 0.0066m 0.0045, and 0.0049. What does this mean?

Thanks,
Rebecca

**Comment by simonhmartin** [comment]
Hi Rebecca,
Thanks for this useful feedback. Is there anything that is incorrect in the README that I should update? (I haven't changed it in ages).
Regarding your question, if you have diploid data, the diagonal represents the genetic distance between the two alleles in each individual, which is equivalent to the density of heterozygous sites.
Simon

**Comment by stubbsrl** [comment]
Thanks for getting to my question so quickly. Having that information in the diagonal is quite useful!

No, there isn't anything incorrect in the README but if you have a minute perhaps adding that subsetting samples is recommended (For instance, I first tried all samples and it didn't work, then 12, then 8, and then finally three before it didn't error out because of memory).  Additionally, including that samples should be seperated by spaces and not commas would be useful. Actually, just adding -T and the --samples to the example command would address all of this. 

It would be cool if I could run genetic distance by population (rather than individual) using --popsFile. Just an idea - I have no idea how hard that would be to implement so feel free to ignore :). I'm currently fine running different combinations of samples and averaging out their distance to get an idea of how distant my populations are. 

Rebecca

**Comment by simonhmartin** [comment]
Thanks for the feedback. I have run it on large sets of 50+ individuals, but to do that I think the SNPs heavily by distance using filterGenotypes.py first. I will add some advice to this effect in the readme.
There's no easy way to average by population the way the script is set up, so I think people will have to do that in post-processing.
