### ISSUE TITLE
the error about popgenWindows.py

### ISSUE THREAD

**Issue by yinhongwei4079** [simonhmartin/genomics_general#35]
hi @simonhmartin 
    I have used the script of parseVCFs to the geno.gz file. it worked well and this was the results
![image](https://user-images.githubusercontent.com/24310150/91163941-ef5bab80-e700-11ea-92e2-b57cc16ef043.png). 
   While i run popgenWindows.py , it got  errors ,
Traceback (most recent call last):
  File "/vol3/agis/likui_group/yinhongwei/software/genomics_general/popgenWindows.py", line 381, in <module>
    for window in windowGenerator:
  File "/vol3/agis/likui_group/yinhongwei/software/genomics_general/genomics.py", line 1894, in slidingCoordWindows
    site = reader.nextSite(asDict = extractSpecificGTs)
  File "/vol3/agis/likui_group/yinhongwei/software/genomics_general/genomics.py", line 1852, in nextSite
    self.precompDict, addToPrecomp=self.precompDict["__counter__"]<self.precompDict["__maxSize__"])
  File "/vol3/agis/likui_group/yinhongwei/software/genomics_general/genomics.py", line 1810, in parseGenoLine
    "position": int(lineData[posCol]) if posCol >= 0 else None,
ValueError: invalid literal for int() with base 10: 'POS'
The script code is "${popgenWindows} -w 50000 -m 25000 -g sweep.mac1.chr_all.SNP.geno.gz -o sweep.mac1.csv.txt -f phased -T 4 -p popA -p popB --popsFile pops.txt"
    Could you give me some advice?
                                                                                                                 your sincerely
                                                                                                                 Hongwei Yin

**Comment by simonhmartin** [comment]
Hi, It looks like the problem is the first line in the geno file:
`[['N/N', 'N/N', ...`
That line should not be there. I'm not sure what is causing that. Do you have the latest version of parseVCFs.py?
