### ISSUE TITLE
"ValueError: zero length field name in format" in parseVCF

### ISSUE THREAD

**Issue by rafmarcondes** [simonhmartin/genomics_general#41]
Hi again Simon,

Sorry about so many questions, but what could be causing the error below in parseVCF? When I try it with --skipIndels, I don't get an error, but the geno file seems truncated.
```

[rmarco3@mike1 29SEP2020]$ python /home/rmarco3/bin/simon-martin-scripts/VCF_processing/parseVCF.py -i REMERGED_post_filter_MASKED.recode.vcf > test-keep-indels.geno
Traceback (most recent call last):
  File "/home/rmarco3/bin/simon-martin-scripts/VCF_processing/parseVCF.py", line 369, in <module>
    ploidyMismatchToMissing=args.ploidyMismatchToMissing,expandMulti=args.expandMulti)
  File "/home/rmarco3/bin/simon-martin-scripts/VCF_processing/parseVCF.py", line 173, in getGenotypes
    expandMulti=expandMulti)
  File "/home/rmarco3/bin/simon-martin-scripts/VCF_processing/parseVCF.py", line 135, in getGenotype
    self.genoData[sample]["GT"], ploidy)) 
ValueError: zero length field name in format
```

**Comment by rafmarcondes** [comment]
Update: gatk ValidateVariants raises no issues with my VCF file.

**Comment by simonhmartin** [comment]
I have not seen this error before, but I read that it might be a python version issue. Make sure you are using python 2.7 or above.

**Comment by rafmarcondes** [comment]
I'll play around with Python versions more tomorrow, but I just wanted to note for now that that was using 3.6.4

**Comment by simonhmartin** [comment]
If you were using 3.6, then I don't think the version is the issue. This one is a bit of a mystery to me. If you send me a small portion of your vcf I might be able to diagnose the problem.

**Comment by rafmarcondes** [comment]
It ran fine in Python 2.7.16. I have attached the first 10000 lines of my vcf to help you troubleshoot.

[simon.vcf.zip](https://github.com/simonhmartin/genomics_general/files/5356045/simon.vcf.zip)

**Comment by simonhmartin** [comment]
Thanks for sending. The 10000 lines includes only the header (you seem to have a large number of contigs). Could you send a larger section? Alternatively, you could skip most of the header lines, as I only need the very last header line that starts with "#CHROM"
