### ISSUE TITLE
popgenWindows.py error

### ISSUE THREAD

**Issue by Andrinajoro** [simonhmartin/genomics_general#44]
Hi Simon,
used  popgenWindows.py from your general genomics pakage to estimate diversity and divergence. 
I was running the following command:
python popgenWindows.py -w 50000 -m 5000 -s 50000 --windType coordinate -g all_rename_filter2_geno0_phased_renammed_chr.geno.gz -o all.Fst.Dxy.pi.csv.gz -f phased -T 8 -p ang ang -p bux bux -p der der -p eur eur -p imb imb -p ory ory -p scr scr -p spe spe -p str str -p syl syl

and got the following message:
Starting 8 worker threads
Traceback (most recent call last):
  File "popgenWindows.py", line 420, in <module>
    exclude = scafsToExclude)
TypeError: slidingCoordWindows() got an unexpected keyword argument 'headerLine'

I rechecked everithing but could not find out what I am doing wrog. 
Your advice would be much appreciated
Joro

**Comment by Andrinajoro** [comment]
Hi Simon
Could it be a python compatibility issue (currently running python 3.7) or numpy (v 1.19.2)? When running  
python2 popgenWindows.py -w 50000 -m 5000 -s 50000 --windType coordinate -g all_rename_filter2_geno0_phased_renammed_chr.geno.gz -o all.Fst.Dxy.pi.csv.gz -f phased -T 8 -p ang ang -p bux bux -p der der -p eur eur -p imb imb -p ory ory -p scr scr -p spe spe -p str str -p syl syl

Traceback (most recent call last):
  File "popgenWindows.py", line 6, in <module>
    import numpy as np
ImportError: No module named numpy

Joro

**Comment by simonhmartin** [comment]
Hi Joro,
This looks like a bug introduced with the latest version of the script that I uploaded. For now, if you go to the previous version here:
https://github.com/simonhmartin/genomics_general/tree/566e04a4d6df9b2dfa0673fdf306ad891564c725
it should hopefully work. I will try to fix the bug when I get a chance.
Simon

**Comment by Andrinajoro** [comment]
Hi Simon,
Thanks for your help. Cloned the previous version as you advised and it
works fine. Thanks for the awesome packages.
Joro

**Comment by simonhmartin** [comment]
Hi Joro,
I just got around to looking for this error, but I don't see a problem in the script. I think the problem might have been that you didn't have the latest version of genomics.py, which was needed to make popgenWindows.py work correctly. If you have a chance to try with the current version, I would be interested to know if it works without error.
Thanks,
Simon

**Comment by Andrinajoro** [comment]
Hi Simon
Will give it a try and get back to you.
Thanks
Joro
