### ISSUE TITLE
Error when running popgenWindows.py 

### ISSUE THREAD

**Issue by melodysyue** [simonhmartin/genomics_general#46]
Hi Simon,
I was running the following command:
CHR="NC_042546.1"
SCRIPT=/scripts/genomics_general/popgenWindows.py
INPUT=/geno_chr/${CHR}.geno.gz
OUTPUT=/stats/${CHR}_dxy_wood.txt
POP=/popmap/pops.wood.txt
WINDOW=100000
STEP=25000
MIN=500
NTHREADS=10
python $SCRIPT -g $INPUT -f diplo -o $OUTPUT -w $WINDOW -m $MIN -s $STEP -p AGUL -p ANVB -p TEAL --popsFile $POP --writeFailedWindows -T $NTHREADS

I got the following message:
Starting 10 worker threads
Process Process-2:
Traceback (most recent call last):
  File "/cm/shared/applications/Python/2.7.16/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/cm/shared/applications/Python/2.7.16/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch-lustre/peuclide/Sockeye/raw_data_1/yue/scripts/genomics_general/popgenWindows.py", line 44, in stats_wrapper
Process Process-1:
Traceback (most recent call last):
  File "/cm/shared/applications/Python/2.7.16/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    Aln = genomics.genoToAlignment(window.seqDict(), sampleData, genoFormat = genoFormat)
  File "/scratch-lustre/peuclide/Sockeye/raw_data_1/yue/scripts/genomics_general/genomics.py", line 1051, in genoToAlignment
    seqList = splitSeq(seqDict[indName], genoFormat)
  File "/scratch-lustre/peuclide/Sockeye/raw_data_1/yue/scripts/genomics_general/genomics.py", line 380, in splitSeq
    if genoFormat == "diplo": sequence = [haplo(d) for d in sequence]
  File "/scratch-lustre/peuclide/Sockeye/raw_data_1/yue/scripts/genomics_general/genomics.py", line 27, in haplo
    def haplo(diplo): return diploHaploDict[diplo]
KeyError: '.'
    self.run()
  File "/cm/shared/applications/Python/2.7.16/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch-lustre/peuclide/Sockeye/raw_data_1/yue/scripts/genomics_general/popgenWindows.py", line 44, in stats_wrapper
    Aln = genomics.genoToAlignment(window.seqDict(), sampleData, genoFormat = genoFormat)
  File "/scratch-lustre/peuclide/Sockeye/raw_data_1/yue/scripts/genomics_general/genomics.py", line 1051, in genoToAlignment
Process Process-3:
Traceback (most recent call last):
  File "/cm/shared/applications/Python/2.7.16/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/cm/shared/applications/Python/2.7.16/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch-lustre/peuclide/Sockeye/raw_data_1/yue/scripts/genomics_general/popgenWindows.py", line 44, in stats_wrapper
    seqList = splitSeq(seqDict[indName], genoFormat)
  File "/scratch-lustre/peuclide/Sockeye/raw_data_1/yue/scripts/genomics_general/genomics.py", line 380, in splitSeq
    if genoFormat == "diplo": sequence = [haplo(d) for d in sequence]
  File "/scratch-lustre/peuclide/Sockeye/raw_data_1/yue/scripts/genomics_general/genomics.py", line 27, in haplo
    def haplo(diplo): return diploHaploDict[diplo]
KeyError: '.'

I am pretty sure that the input geno file is the correct format, see blow:
![Screen Shot 2020-11-17 at 2 58 23 PM](https://user-images.githubusercontent.com/35020018/99460797-5db99f80-28e5-11eb-9454-467b517df110.png)

Could you help me figure out why I got the error message? 

Thanks,
Yue

**Comment by simonhmartin** [comment]
Hi Yue,
It seems to be that some of your genotypes are encoded as `.`, is that possible? If so, you should replace them with `N`.
Hope that works,
Simon

**Comment by melodysyue** [comment]
It works! Thank you! 

But it is strange that both "./." and "." are in my genotype file considering the organism is diploid...

Yue

**Comment by simonhmartin** [comment]
Good!
I think some genotypers can include both "./." and "." in the vcf, depending on how much data is available for the particular site.
