### ISSUE TITLE
popgenWindows.py popFreq MemoryError

### ISSUE THREAD

**Issue by genevalab** [simonhmartin/genomics_general#50]
Thank you for providing these tools - they are incredibly useful. I am running into a problem running popFreq analysis. The geno file I have created that works fine for popDist and popPairDist but hangs when running popFreq. 

I am attempting to run using the following command:

`$ python $SCRIPTS/popgenWindows.py -g $GENOS/Mayaguez.geno.gz -w 50000 -s 10000 -m 100 -o $GENOS/Mayaguez.freq_output.csv -f phased -T 1 --windType coordinate --analysis "popFreq" -p urban KMW_344,KMW_558,KMW_563,KMW_575,KMW_586,KMW_589,KMW_605,KMW_616,KMW_623,KMW_626,KMW_632,KMW_633,KMW_641,KMW_647,KMW_659,KMW_661 -p forest KMW_380,KMW_386,KMW_396,KMW_408,KMW_414,KMW_421,KMW_425,KMW_426,KMW_431,KMW_461,KMW_478,KMW_480,KMW_492,KMW_535,KMW_539,KMW_553`

I get the following error:
```
Starting 1 worker threads

211 windows queued, 210 results received, 119 results written.
/home/geneva/apps/genomics_general/genomics.py:625: RuntimeWarning: invalid value encountered in double_scalars
  D = d / np.sqrt(e1*S + e2*S*(S-1))
Process Process-1:
Traceback (most recent call last):
  File "/home/geneva/anaconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/geneva/anaconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/geneva/apps/genomics_general/popgenWindows.py", line 49, in stats_wrapper
    statsDict.update(Aln.groupFreqStats())
  File "/home/geneva/apps/genomics_general/genomics.py", line 993, in groupFreqStats
    siteBaseCounts = np.apply_along_axis(binBaseFreqs,0,self.numArray[np.ix_(seqIdx,siteIdx)],asCounts=True)
  File "<__array_function__ internals>", line 5, in apply_along_axis
  File "/home/geneva/anaconda3/lib/python3.8/site-packages/numpy/lib/shape_base.py", line 402, in apply_along_axis
    buff[ind] = asanyarray(func1d(inarr_view[ind], *args, **kwargs))
  File "/home/geneva/apps/genomics_general/genomics.py", line 592, in binBaseFreqs
    if asCounts: return np.bincount(numArr, minlength=4)
  File "<__array_function__ internals>", line 5, in bincount
MemoryError: Unable to allocate 1020. TiB for an array with shape (140143801524529,) and data type int64
```

It then repeats this line every few minutes, seeming indefinitely:
`211 windows queued, 210 results received, 119 results written.`

There doesn't seem to be anything special about window 120 and if I change the window size the analysis hangs at a totally different coordinate. The same error also occurs with geno files built using other VCFs from other populations. I do not have 1020 TiB of RAM :) but I don't believe that should actually be needed for this analysis.

Many thanks for any ideas you have!

Update - The above occurred using python 3.8.3. A very similar error occurs when using 2.7 with slightly different error syntax:
```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/geneva/apps/genomics_general/popgenWindows.py", line 49, in stats_wrapper
    statsDict.update(Aln.groupFreqStats())
  File "/home/geneva/apps/genomics_general/genomics.py", line 993, in groupFreqStats
    siteBaseCounts = np.apply_along_axis(binBaseFreqs,0,self.numArray[np.ix_(seqIdx,siteIdx)],asCounts=True)
  File "/home/geneva/.local/lib/python2.7/site-packages/numpy/lib/shape_base.py", line 403, in apply_along_axis
    buff[ind] = asanyarray(func1d(inarr_view[ind], *args, **kwargs))
  File "/home/geneva/apps/genomics_general/genomics.py", line 592, in binBaseFreqs
    if asCounts: return np.bincount(numArr, minlength=4)
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
```

**Comment by simonhmartin** [comment]
Hi, sorry about the long delay!
I can't immediately figure out what the problem is. Would it be possible to share a portion of your geno file so that I could try recreating this error locally?

**Comment by simonhmartin** [comment]
Hi, I think I know the problem. Your .geno file cannot contain the '*' character. I will try make an update soon that addresses this, but for now you will need to replace those with 'N' yourself

**Comment by genevalab** [comment]
Hello Simon,
Thank you. I am sorry to have not replied sooner. My semester just ended and I am only now getting back to this project. I just check my .geno files and they do indeed include many "*" characters. I have changed them all to "N" and it solved the issue. 
Thank you so much for staying on top of this issue despite my silence. I really appreciate it!
