### ISSUE TITLE
Empty output file with raxml_sliding_windows.py script

### ISSUE THREAD

**Issue by schsarah** [simonhmartin/genomics_general#58]
Hi Simon, 
Hope you are doing well!

I would like to reconstruct phylogenies in sliding windows using both your `phyml_sliding_windows.py` and `raxml_sliding_windows.py`. The phyml script is working perfecftly with my dataset, but when I tried to run the raxml script with the same dataset I got several error messages. I realized that it was because the script was not compatible with python3, so I updated the script for python3 compatibility (see attached file). Now I can run my analysis with the following command line:
```
python3.6 genomics_general/raxml_sliding_windows.py -g input_geno/with_outgroup/chr24.ATLAS_majorMinor_clarkii_aki_color_subset.minQ40minDepth2.minInd.geno --outgroup AK003,AK038,AK055 --prefix chr24_clarkii_outgroup_color_subset_raxml_w5000 -w 5000 --windType sites --raxml raxmlHPC --verbose
```
But I get the following message:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "genomics_general/raxml_sliding_windows.py", line 113, in writer
    treesFile.write(tree)
  File "/usr/lib64/python3.6/gzip.py", line 260, in write
    data = memoryview(data)
TypeError: memoryview: a bytes-like object is required, not 'str'
```
However, the analysis keeps on running, but the output files are empty (according to the message, no result is written in the file):

```
Sending window 1 to queue. Length: 5000
Window 1 received for analysis, length: 5000
Sorter received result 1
Result 1 sent to writer
Sending window 2 to queue. Length: 5000
Window 2 received for analysis, length: 5000
Sorter received result 2
...

Writing final results...

139 windows queued |  139 results received |  0 results written.
139 windows queued |  139 results received |  0 results written.
139 windows queued |  139 results received |  0 results written.
```
Do you have any clue on how to fix it? I've been struggling with that since a few days now and didn't manage to find the solution. 

Thanks a lot in advance for your help :)

Sarah

[raxml_sliding_windows_python3.txt](https://github.com/simonhmartin/genomics_general/files/6883764/raxml_sliding_windows_python3.txt)

**Comment by simonhmartin** [comment]
Hi Sarah,
Nice to hear from you and sorry to hear you've been struggling with this!
Yes this is a script I have not updated in years and the one on my repo is still not compatible with python3. To fix the error you're getting, you need to convert "r" to "rt" in lines 39 and 219 (two places in 219), and convert "w" to "wt" in lines 223 and 226. These changes are because python3 by default reads files as bytes rather than plain text, and these changes specify that it should use plain text. I hope it runs after this!
Simon

**Comment by schsarah** [comment]
It's working! Thanks a lot Simon for your quick help :)
