### ISSUE TITLE
bug in fourPopWindows.py

### ISSUE THREAD

**Issue by nelidapg** [simonhmartin/genomics_general#66]
Hi Martin,
I have a bug in fourPopWindows.py. Could you assist with that, please?

Traceback (most recent call last):
  > File "fourPopWindows.py", line 345, in <module>
>     for window in windowGenerator:
> File "/abba_baba/genomics_general/genomics.py", line 1930, in slidingCoordWindows
>    GTs = [site["GTs"][name] for name in names] if extractSpecificGTs else site["GTs"]
>  File "/abba_baba/genomics_general/genomics.py", line 1930, in <listcomp>
>    GTs = [site["GTs"][name] for name in names] if extractSpecificGTs else site["GTs"]
KeyError: 'TIS_01ta'

TIS_01ta is the name of the first sample of P1 in my geno file 

It seems that the error is the same that you found ABBABABAwindows.py some time ago. See here:

Thank you for your reply.
The SimpleQueue issue is resolved, thank you.
Now I have a new error 
Traceback (most recent call last):
  

> File "ABBABABAwindows.py", line 312, in <module>
>     for window in windowGenerator:
>   File "/Merged_Final/window/py3/genomics.py", line 1894, in slidingCoordWindows
>     GTs = [site["GTs"][name] for name in names] if extractSpecificGTs else site["GTs"]
>   File "/Merged_Final/window/py3/genomics.py", line 1894, in <listcomp>
>     GTs = [site["GTs"][name] for name in names] if extractSpecificGTs else site["GTs"]
> KeyError: 'CB11'

Note: CB11 is the name of the first sample in my geno.

I reordered the samples in the pops file to match the order in the geno file, and I get the same error with another sample name.
Update:
I get the error with samples associated with the first population (P1)
Please assist,
Thank you,

_Originally posted by @foala in https://github.com/simonhmartin/genomics_general/issues/28#issuecomment-649616893_

**Comment by simonhmartin** [comment]
Hi,
Have you checked whether the solution from the previous issue is the same in this case? Multi-base genotypes like `AAA/A` cannot be parsed by my script, and removal of these seemed to fix the problem previously.
Simon
