### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '(most'

### ISSUE THREAD

**Issue by ShirelyI** [simonhmartin/genomics_general#85]
Hi Martin,
When I ran 'python ./genomics_general_master/popgenWindows.py -w 50000 -m 1000 -g final.geno.gz -o final.csv.gz -f phased -T 20 -p MA -p MP -p MS -p MT --popsFile pop.list' ,the log shows as follows :

Starting 20 worker threads

213 windows queued, 209 results received, 117 results written.
....
1504 windows queued, 1499 results received, 947 results written.
/newlustre/home/yudan/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3420: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/newlustre/home/yudan/miniconda3/lib/python3.7/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/newlustre/home/yudan/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3420: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/newlustre/home/yudan/miniconda3/lib/python3.7/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
...
1851 windows queued, 1844 results received, 1180 results written.
Traceback (most recent call last):
  File "./genomics_general-master/popgenWindows.py", line 434, in <module>
    for window in windowGenerator:
  File "./genomics_general-master/genomics.py", line 1933, in slidingCoordWindows
    site = reader.nextSite(asDict = extractSpecificGTs)
  File "./genomics_general-master/genomics.py", line 1882, in nextSite
    self.precompDict, addToPrecomp=self.precompDict["__counter__"]<self.precompDict["__maxSize__"])
  File "./genomics_general-master/genomics.py", line 1840, in parseGenoLine
    "position": int(lineData[posCol]) if posCol >= 0 else None,
ValueError: invalid literal for int() with base 10: '(most'

I'm deeply troubled by this problem.Could you please help me ?
Thanks a lot 
Best wishes,
ruijin

**Comment by ShirelyI** [comment]
Hi Martin,
I noticed that the scripts are written in Python2  but my working environment is Python3 , is  the problem here?
Best wishes,
ruijin

**Comment by simonhmartin** [comment]
Hi Ruijin,
This script is compatible with both python 2 and 3.
Your error says `ValueError: invalid literal for int() with base 10: '(most'`
It seems that somewhere in your input file, in a place where the script is expecting to see the position, it instead found the text `(most`. Can you try grep for this to check if it is indeed in your input file?

**Comment by ShirelyI** [comment]
Hi Martin,
Thanks for your reply.
I  found that the size of vcf is 9.5G while the geno file is only 44M, then I checked the input file and found the follow message:

Traceback (most recent call last):
  File "./genomics_general_master/VCF_processing/parseVCF.py", line 377, in <module>
    ploidyMismatchToMissing=args.ploidyMismatchToMissing,expandMulti=args.expandMulti)
  File "./genomics_general_master/VCF_processing/parseVCF.py", line 177, in getGenotypes
    expandMulti=expandMulti)
  File "./genomics_general_master/VCF_processing/parseVCF.py", line 139, in getGenotype
    self.genoData[sample]["GT"], ploidy)) 
ValueError: Sample GQ4 at NC_063045.1:17234877 genotype . does not match explected ploidy of 2

It says the GQ4 genotype at NC_063045.1:17234877 does not match explected ploidy of 2 ,then I checked the vcf file it shows" .:0,0:6:0:0|1:17234876_C_G:0,0,0:17234876" ,the GT is truly in wrong format .

I'll try to regenerate the geno file,do you know how solve the problem Martin?
Best wishes,
Ruijin
