### ISSUE TITLE
Possible issue with the new filterGenotypes.py

### ISSUE THREAD

**Issue by DaniPaulo** [simonhmartin/genomics_general#86]
First of all, thanks for the useful scripts! I'm writing to let you know about a possible problem with the new `filterGenotypes.py` (ca77a3c at the Master). I've been trying to run filterGenotypes.py on my data and getting the following warnings:

`Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genomics/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/genomics/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./martin_simon/filterGenotypes.py", line 103, in writer
    if verbose:
NameError: name 'verbose' is not defined`

After that, the program keeps printing the following message and never complete the analysis:

`310000 lines read | 30 pods queued | 13 pods filtered | 11 pods sorted | 0 pods written | 0 good lines written.`

My command is `python filterGenotypes.py -i cohort_GenotypeGVCFs.vcf.geno.gz -o cohort_GenotypeGVCFs.vcf.filtered.geno.gz -t 5 -p BP A03.black,A04.black -p WT A06.brown,A08.brown --minPopCalls 1 --minCalls 2 --minAlleles 2`

I'm using `Python 3.7.12`. The input file (cohort_GenotypeGVCFs.vcf.geno.gz) was generated using `parseVCFs.py` and the final .vcf file generated by GATK pipeline (HaplotypeCaller -> CombineGVCFs -> GenotypeGVCFs). I was trying to filter my geno file before running `popgenWindows.py`, cause I have too many missing genotypes (N/N). An example:

`#CHROM  POS     A03.black       A04.black       A06.brown       A08.brown
Chromosome1     41558   N/N     N/N     N/N     N/N
Chromosome1     54352   T/T     N/N     N/N     N/N
Chromosome1     54567   T/C     N/N     N/N     N/N
Chromosome1     56344   N/N     N/N     N/N     N/N
Chromosome1     56543   N/N     N/N     N/N     N/N
Chromosome1     79157   N/N     N/N     N/N     N/N
Chromosome1     79270   N/N     N/N     N/N     N/N
Chromosome1     81473   N/N     N/N     N/N     N/N
Chromosome1     88759   N|N     N/N     N/N     N/N
Chromosome1     88771   N|N     N/N     N/N     N/N
Chromosome1     89970   G/G     G|A     G/G     G/G
Chromosome1     89979   C/C     C|T     C/C     C/C
Chromosome1     90036   C/G     C/G     C/G     C|G
Chromosome1     90042   G/G     G/G     G/G     G|A
Chromosome1     90079   C/A     C/C     C/A     C/C
Chromosome1     90745   T/T     T/T     T/C     T/T
Chromosome1     90927   N/N     N/N     C/G     C/G
Chromosome1     91120   N/N     C/C     C/A     C/A
Chromosome1     91234   N/N     N/N     N/N     G/C
Chromosome1     91419   N/N     C/C     C/C     C/C
Chromosome1     91645   G/G     G/T     G/G     G/G
Chromosome1     91652   N|N     C/C     N/N     C/C`

I end up trying an earlier version of your script (download from: `https://github.com/simonhmartin/genomics_general/tree/566e04a4d6df9b2dfa0673fdf306ad891564c725`), and it seems to work just fine:

`1344063 lines read | 134 pods queued | 129 pods filtered | 129 pods sorted | 129 pods written | 13222 good lines written.
2660000 lines read | 265 pods queued | 260 pods filtered | 260 pods sorted | 260 pods written | 24938 good lines written.
3970000 lines read | 396 pods queued | 391 pods filtered | 391 pods sorted | 391 pods written | 38494 good lines written.
4744589 lines read | 475 pods queued | 475 pods filtered | 475 pods sorted | 475 pods written | 47186 good lines written.`

So I'm just writing to let you know about this postential issue. I can send my input file to you if you want to.
Cheers,

- Dani.

**Comment by simonhmartin** [comment]
Thanks Dani for letting me know. Yes that's a bug I accidentally added recently. I will upload a fixed version soon.
