### ISSUE TITLE
Something wrong with popgenWindows.py

### ISSUE THREAD

**Issue by SunJJ230120** [simonhmartin/genomics_general#93]
Hi Simon, I'm having some issues running with this script.

python3 popgenWindows.py -w 100000 -g output.geno.gz -o output.csv -f phased -T 4 -p P1 -p P2_1 -p P2_2 -p P2_3 -p P3 --popsFile group.txt

The results output.csv was in the file folder, but the wrong message as follows:

Starting 4 worker threads
43 windows queued, 39 results received, 39 results written.
.
.
.
68666 windows queued, 68662 results received, 67450 results written.
Traceback (most recent call last):
  File "genomics_general-master/popgenWindows.py", line 436, in <module>
    for window in windowGenerator:
  File "genomics_general-master/genomics.py", line 1930, in slidingCoordWindows
    GTs = [site["GTs"][name] for name in names] if extractSpecificGTs else site["GTs"]
  File "genomics_general-master/genomics.py", line 1930, in <listcomp>
    GTs = [site["GTs"][name] for name in names] if extractSpecificGTs else site["GTs"]
KeyError: 'P3_152'

The vcf filtering using vcftools with --max-missing 0.95 --maf 0.05 --remove-indels --min-alleles 2 --max-alleles 2, what causes this error?

could you please help me to solve it?
Many thanks!

Best,
Stephanie

**Comment by simonhmartin** [comment]
Hi Stephanie,
I just noticed that I missed your query. Did you manage to solve it yet? I don't think I've seen this kind of issue before, so it might be necessary to share the input file so I can diagnose the problem.
Simon
