### ISSUE TITLE
AssertionError: Sample ploidy (2) doesn't match number of sequences (8)

### ISSUE THREAD

**Issue by Ashu2195** [simonhmartin/genomics_general#96]
Dear Simon
I'm getting an error when I'm using the "popgenWindows.py" script. When I'm using -w 50000 -s 50000 it's working fine, but when I'm using -w 10000 -s 10000 then, it shows this error.

Starting 1 worker threads
/home/ceglab5/miniconda3/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/ceglab5/miniconda3/lib/python3.9/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

1504 windows queued, 1501 results received, 1501 results written.

3009 windows queued, 3006 results received, 3006 results written.

4527 windows queued, 4524 results received, 4524 results written.

5998 windows queued, 5996 results received, 5996 results written.

7529 windows queued, 7518 results received, 7518 results written.
Process Process-1:
Traceback (most recent call last):
  File "/home/ceglab5/miniconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ceglab5/miniconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ceglab5/Desktop/winfiles/abbabab/new_soft/data/genomics_general-master/ashu/../popgenWindows.py", line 44, in stats_wrapper
    Aln = genomics.genoToAlignment(window.seqDict(), sampleData, genoFormat = genoFormat)
  File "/home/ceglab5/Desktop/winfiles/abbabab/new_soft/data/genomics_general-master/genomics.py", line 1076, in genoToAlignment
    if ploidy is not None: assert len(seqList) == ploidy, "Sample ploidy (" + str(ploidy) + ") doesn't match number of sequences (" + str(len(seqList)) + ")"
AssertionError: Sample ploidy (2) doesn't match number of sequences (8)

7633 windows queued, 7606 results received, 7604 results written.

7633 windows queued, 7606 results received, 7604 results written.

**Comment by simonhmartin** [comment]
This error suggests that you multi-base variants like `A/AA` in the geno file. This script cannot work with such variants, so they should be excluded.
Simon
